//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Properties.ConsoleTexts", typeof(ConsoleTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Show all Blocks
        ///2 - Show full information about City
        ///3 - Show area of City
        ///4 - Show area by a person in City
        ///5 - Show houses by project types
        ///6 - Show one- and nine-story houses
        ///7 - Show new houses (year is bigger than 2015)
        ///8 - Show happy houses (has 7 in code)
        ///9 - Show project types which consists of 5 floats
        ///10 - Find administration by house code
        ///11 - Show information about the biggest Block
        ///12 - Show Top 10 oldest houses
        ///13 - Show percent of HighRise houses by Block
        ///14 - Show blocks wit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks with multi-entrences houses:.
        /// </summary>
        internal static string MultiEntrencesHousesLabel {
            get {
                return ResourceManager.GetString("MultiEntrencesHousesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project types which consists of 5 or more floats:.
        /// </summary>
        internal static string SpecificTypesLabel {
            get {
                return ResourceManager.GetString("SpecificTypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The biggest Block consists of:.
        /// </summary>
        internal static string TheBiggestBlockLabel {
            get {
                return ResourceManager.GetString("TheBiggestBlockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS-02 - Zozuliuk Viktor - Variant 6.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
